### ISSUE TITLE
Elliot - Web Developer Role

### ISSUE THREAD

**Issue by JoelInman-Dev** [ElliotJasper/lastmanstanding#2]
Hello Elliot, 

We were contacted by an agency representing you as a web developer.

I wondered if we could have a chat and if it would be possible to get some contact information from you, whether an email address or a contact number?

Many thanks,

Joel

**Comment by ElliotJasper** [comment]
Hi Joel. This is my email, ***@***.***

**Comment by JoelInman-Dev** [comment]
Hi Elliot, 
Github redacted your email from your message. however, I have managed to scrape it from one of your recent commit events though.

I have sent you an email over to elliotjasperis [at] gmail [dot] com.

**Comment by ElliotJasper** [comment]
The only email I've received is the comment on the issue?

**Comment by JoelInman-Dev** [comment]
That's odd. Okay, just incase it's not in your spam folder - my obvious next suggestion.

Do you want to pop me an email to webdev [at] darksidedevelopments [dot] co [dot] uk

**Comment by ElliotJasper** [comment]
Emailed
