### ISSUE TITLE
Users should be able to update profile

### ISSUE THREAD

**Issue by ElliotJasper** [ElliotJasper/lastmanstanding#24]
- Users should be able to update display name
- User should be able to have profile pick
- Will need to update the profile table to have PFP url

**Comment by AAigars** [comment]
I strongly support adding the display name and profile picture features to our site—these updates are crucial for improving user experience and engagement on our platform. Updating the profile table with a PFP URL is essential, and I believe prioritizing this will significantly enhance our users’ connection to the site.

Looking forward to seeing this implemented soon.

**Comment by ElliotJasper** [comment]
Ofcourse! However, I suppose I need to look into some sort of content moderation to prevent abuse!!

**Comment by AAigars** [comment]
Great idea! We can use machine learning for content moderation—image recognition to filter profile pics and NLP models to catch offensive language in display names. This setup should keep everything compliant and user-friendly!

**Comment by ElliotJasper** [comment]
Absolutely, I will delegate this task to you!!
