### ISSUE TITLE
Deploy via Vercel

### ISSUE THREAD

**Issue by LiamKenyon** [ElliotJasper/lastmanstanding#6]
Hi Bud.

Been keeping an eye on this as it was something I was going to create myself.

Have you any plans to incorporate running via Vercel etc… 

As I can help with that or create a separate fork for it etc…

**Comment by ElliotJasper** [comment]
Hi Liam,

Currently I don't have any plans to deploy as it's still a work in progress I do in my spare time, and is a long way off that!

Feel free to fork for yourself though.
